# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 17:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pics', '0002_auto_20160131_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='PictureRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveSmallIntegerField()),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pics.Picture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
