# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 19:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0003_picturerate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='picturerate',
            unique_together=set([('picture', 'user')]),
        ),
    ]
