# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 20:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0007_auto_20160202_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='picturerate',
            name='picture',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pics.Picture'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='picturerate',
            unique_together=set([('picture', 'user')]),
        ),
    ]
